Repository prefix-dev/setup-pixi, pull requests merged in 2024-05, with the labels that each got.

#109 Fix CI
  .github/workflows/test.yml
  README.md
  test/no-lockfile/pixi.toml
Labels: ci

#108 Add `activate-environment` option
  .github/workflows/build.yml
  .github/workflows/test.yml
  README.md
  action.yml
  dist/index.js
  dist/post.js
  package.json
  src/activate.ts
  src/main.ts
  src/options.ts
  src/util.ts
Labels: enhancement

#113 Fix saving cache taking too long
  README.md
  dist/index.js
  package.json
  src/main.ts
Labels: bug

#116 Improve `run-install` wording
  action.yml
Labels: documentation

#118 fix: use iarna/toml instead of toml
  .github/workflows/build.yml
  README.md
  dist/index.js
  dist/post.js
  package.json
  pnpm-lock.yaml
  src/options.ts
  test/pyproject-manifest/pyproject.toml
  tsup.config.js
Labels: bug
