Repository prefix-dev/setup-pixi, pull requests merged in 2024-02, with the labels that each got.

#69 Add pixi list to output
  .github/workflows/test.yml
  README.md
  dist/index.js
  src/main.ts
Labels: enhancement

#70 Add support for multiple envs
  .github/workflows/build.yml
  .github/workflows/test.yml
  README.md
  action.yml
  dist/index.js
  dist/post.js
  package.json
  src/cache.ts
  src/main.ts
  src/options.ts
  src/util.ts
  test/multiple-environments/pixi.lock
  test/multiple-environments/pixi.toml
Labels: enhancement

#74 Fix typos
  README.md
Labels: documentation

#75 Add warning about caching with multi-envs
  README.md
Labels: documentation

#76 Fix cache-write behavior
  .github/workflows/test.yml
  README.md
  dist/index.js
  dist/post.js
  package.json
  src/options.ts
Labels: bug

#77 Add no-pixi-toml test
  .github/workflows/test.yml
Labels: ci

#79 Add `pwsh` as pixi shells to the tests and documentation
  .github/workflows/test.yml
  README.md
Labels: documentation
