Repository prefix-dev/setup-pixi, pull requests merged in 2024-04, with the labels that each got.

#94 fix: respect frozen/locked inputs for pixi list
  .github/workflows/test.yml
  dist/index.js
  src/main.ts
Labels: bug

#95 fix: restoring cache for pyproject.toml
  .github/workflows/test.yml
  README.md
  dist/index.js
  dist/post.js
  package.json
  src/options.ts
  test/pyproject-manifest/pixi.lock
  test/pyproject-manifest/pyproject.toml
Labels: bug

#98 support preinstalled local pixi
  .github/workflows/test.yml
  README.md
  dist/index.js
  dist/post.js
  package.json
  pnpm-lock.yaml
  src/main.ts
  src/options.ts
  tsup.config.js
Labels: enhancement

#87 Add better support for pyproject.toml pixi projects
  .github/workflows/build.yml
  .github/workflows/test.yml
  .gitignore
  README.md
  dist/index.js
  dist/post.js
  package.json
  pnpm-lock.yaml
  src/options.ts
  test/pyproject-manifest/pyproject.toml
  tsup.config.js
Labels: enhancement

#100 chore: align docs with pixi
  README.md
Labels: documentation
